### ISSUE TITLE
Fighting the borrow checker a bit too much.

### ISSUE THREAD

**Issue by hasenbanck** [leudz/shipyard#122]
Hi,

I'm currently trying to port a game of mine from hecs to shipyard 5.0.

In the process I currently need to fight the borrow checker a bit too much, since the `Mut` is overly protective:

Code without the ECS, which will run fine without the borrow checker moaning:

```rust
  let mut ai = Ai::default();
  for score in ai.action_scores.iter_mut() {
      let mut weight = score.action.weight();

      // If an action is currently running, this action will get an extra modifier bonus.
      if score.action == ai.action && ActionStatus::InProgress == ai.action_status {
          weight *= 1.5
      }

      // Apply the cooldown.
      if let Some(cooldown) = ai.action_cooldowns.get(&score.action) {
          weight -= cooldown;
      }

      score.score *= weight;
  }
```

If the Ai struct is behind a `Mut`, because I iterate over all `Ai`'s in a `ViewMut<Ai>`, I get the following compiler errors.

This error could be fixed by copying/clone the ai.action beforehand:

```rust
55 |         for score in ai.action_scores.iter_mut() {
   |                      ---------------------------
   |                      |
   |                      mutable borrow occurs here
   |                      mutable borrow later used here
...
59 |             if score.action == ai.action && ActionStatus::InProgress == ai.action_status {
   |                                ^^ immutable borrow occurs here
```

But this one is curently giving me headaches:

```rust
55 |         for score in ai.action_scores.iter_mut() {
   |                      ---------------------------
   |                      |
   |                      mutable borrow occurs here
   |                      mutable borrow later used here
...
64 |             if let Some(cooldown) = ai.action_cooldowns.get(&score.action) {
   |                                     ^^ immutable borrow occurs here
```

Am I missing something here? What is the intended pattern in such cases?

**Comment by hasenbanck** [comment]
As a quick workaround I moved the HashMap (cooldowns) and the Vec (scores) into seperate components. But this would mean that I need to structures my components around a technical limitation and not functional requirements.

**Comment by colelawrence** [comment]
As a side note, splitting these up into separate components would be the encouraged approach, so the behavior of how cooldowns work can be delegated to a system that only tracks cooldown timers.

This has the advantage of then allowing anything else in your game to have some form of cooldowns and the timer system will continue working.

This is more of an aside, where I might be assuming your X in this X Y problem.

**Comment by leudz** [comment]
I agree with @colelawrence, the names would suggest they are disjointed enough to be separate components.

If you decide to keep them as a single component there are at least two things you can do:

1. Reborrow
You can use `let ai = &mut *ai;` at the start of the loop to get an exclusive reference. Or even use pattern matching to get a reference to each field.

2. Use `FastIter`
The default trait to get an iterator out of views is `IntoIter`.
It's the default because it works with storages that track modification, `IntoFastIter` on the other hand will panic.
If you know this storage does not need to track modification then you can use `fast_iter()` instead of `iter()`.
You'll get back references for both shared and exclusive views.

`Mut` is definitely a trade-off, 0.4 used a different one where there was a custom `Iterator` trait, components were tagged modified "just in case" and the iterator yielded references.
I don't think a perfect api can be reached on this with modification tracking. But I'd be happy to be wrong.

**Comment by hasenbanck** [comment]
@leudz Thank you for pointing out the existence of `FastIter`, I will use it in these cases from now on.

Some user feedback about the API:

Currently the tracking of modifications is "opt-in". I explicitly have to tag my component stores to track modifications. So the current default behavior of components is not to track modifications.

`IntoIter` on the other hand changes the default behavior of the borrow mechanics, since it want's to be compatible with this "opt-in" feature. So in a sense, I have to "opt-out" to get the "default", or "expected" borrow behavior.

This feels disjointed.

Since I now understand this works as designed and have some workarounds, I will close this issue.
