### ISSUE TITLE
crates.io - yanked versions

### ISSUE THREAD

**Issue by MartinKavik** [leudz/shipyard#129]
Hello,
why, please, are all previous versions yanked? (https://crates.io/crates/shipyard/versions) Was it an accident or something like that? I'm asking because It has broken [Seed](https://seed-rs.org/) pipeline.

**Comment by leudz** [comment]
Hello, I'm sorry I broke your pipeline.
This is not an accident, when 0.5 was released I yanked 0.3 and 0.4 because it was possible to trigger UB.
If I recall correctly for 0.4 it was by reversing an iterator with tracking filter.

I can make a PR to Seed to update it, would that be good enough to fix your issue?

**Comment by leudz** [comment]
I unyanked all versions.
While researching the subject I found this [reddit post](https://www.reddit.com/r/rust/comments/ctayew/rust_crypto_developers_please_stop_the_yanking/) talking about yanking in the crypto ecosystem.
What made me change my mind is the mention of `bisect`. Even if binaries keeping their `Cargo.toml` should be able to compile yanked crates, trying to `bisect` a library would fail.

So I won't yank any future version but non latest versions might have difficult to spot bugs.
