### ISSUE TITLE
Add flagged/tracked storage to the book

### ISSUE THREAD

**Issue by schell** [leudz/shipyard#131]
This library looks great! Thanks for all your hard work and good docs. I'm thinking about switching to shipyard from specs, but I haven't yet read about flagged/tracked storages. I see there are some types in the docs, but I'm not sure how to put them together.

**Comment by leudz** [comment]
Thanks for pointing it out! It was present in a previous version but was deleted by mistake apparently.
I'll make sure to fix that before the next release, in the meantime I can walk you through it.

Tracking went through a big change a few months ago.
For users what changed is the way you declare it so I'm going to explain for both separately.

You can track _insertion_, _modification_, _deletion_ and _removal_.
_deletion_ will store the component in the tracking info whereas _removal_ will give it back imediately.
It can be noticed on [`SparseSet::delete`](https://docs.rs/shipyard/0.5.0/shipyard/struct.SparseSet.html#method.delete) vs [`SparseSet::remove`](https://docs.rs/shipyard/0.5.0/shipyard/struct.SparseSet.html#method.remove) signatures:
```rust
fn delete(&mut self, entity: EntityId) -> bool {}
fn remove(&mut self, entity: EntityId) -> Option<T> {}
```
Components can be _deleted_ or _removed_ but whole entities can only be _deleted_ (at least for now, it's technically possible to return something but I digress :sweat_smile:).

## 0.5

Any combination of tracking is valid.
You define it by calling functions on [`SparseSet`](https://docs.rs/shipyard/0.5.0/shipyard/struct.SparseSet.html) that you can get by borrowing a `ViewMut` either in a system or with `borrow`.
Here's the list: [`track_insertion`](https://docs.rs/shipyard/0.5.0/shipyard/struct.SparseSet.html#method.track_insertion), [`track_modification`](https://docs.rs/shipyard/0.5.0/shipyard/struct.SparseSet.html#method.track_modification), [`track_deletion`](https://docs.rs/shipyard/0.5.0/shipyard/struct.SparseSet.html#method.track_deletion), [`track_removal`](https://docs.rs/shipyard/0.5.0/shipyard/struct.SparseSet.html#method.track_removal) and [`track_all`](https://docs.rs/shipyard/0.5.0/shipyard/struct.SparseSet.html#method.track_all).
And you can chain them if you are doing something fancy.

For example:
```rust
fn setup_tracking(mut u32s: ViewMut<u32>) {
    u32s.track_insertion().track_modification();
}
```

Tracking will start right after the function call and everything starts not flagged. So even if you already have components inside, they won't be flagged _inserted_.

Unique components (resources) always track _modification_ and only that.

## Master

The big change on master is that components have to implement a `Component` trait (basically like `specs`).
But where `specs` uses `Component` to declare the component storage, shipyard declares tracking.
Any individual tracking or all of them is valid.
The list: `track::Untracked`, `track::Insertion`, `track::Modification`, `track::Deletion`, `track::Removal` and `track::All`.

Example:
```rust
struct Position(f32, f32);
impl Component for Life {
    type Tracking = track::Untracked;
}

struct Life(f32);
impl Component for Life {
    type Tracking = track::All;
}
```
or with a proc macro (requires the `proc` cargo feature)
```rust
#[derive(Component)]
struct Position(f32, f32);

#[derive(Component)]
#[track(All)]
struct Life(f32);
```

Tracking will start as soon as the storage is created.

Unique components (resources) can track _insertion_ or _modification_. They also have to implement the `Component` trait.

## Common

You can query _inserted_ and _modified_ components when iterating by calling `inserted`, `modified` or `inserted_or_modified` on a view before making the iterator. (`*_mut` versions also exist)
You can iterate multiple views even if you are filtering with `modified` for example.

Example:
```rust
fn run(u32s: ViewMut<u32>, usizes: View<usize>) {
    for (mut i, j) in (&mut u32s, usizes.inserted()).iter() {
        // only get the entities with both u32 and usize components where usize was inserted recently
    }
}
```

_deleted_ and _removed_ are a bit different since they are not part of the storage.
There is [`deleted`](https://docs.rs/shipyard/0.5.0/shipyard/struct.SparseSet.html#method.deleted), [`removed`](https://docs.rs/shipyard/0.5.0/shipyard/struct.SparseSet.html#method.removed) and [`removed_or_deleted`](https://docs.rs/shipyard/0.5.0/shipyard/struct.SparseSet.html#method.removed_or_deleted) if you just want the information.
[`take_deleted`](https://docs.rs/shipyard/0.5.0/shipyard/struct.SparseSet.html#method.take_deleted), [`take_removed`](https://docs.rs/shipyard/0.5.0/shipyard/struct.SparseSet.html#method.take_removed) and [`take_remove_and_deleted`](https://docs.rs/shipyard/0.5.0/shipyard/struct.SparseSet.html#method.take_removed_and_deleted) will give you back the tracking information in addition to remove it from the storage.

When you want to clear _insertion_ or _modification_ tracking information from a storage there is: [`clear_all_inserted`](https://docs.rs/shipyard/0.5.0/shipyard/struct.SparseSet.html#method.clear_all_inserted), [`clear_all_modified`](https://docs.rs/shipyard/0.5.0/shipyard/struct.SparseSet.html#method.clear_all_modified) and [`clear_all_inserted_and_modified`](https://docs.rs/shipyard/0.5.0/shipyard/struct.SparseSet.html#method.clear_all_inserted_and_modified).
There is also a version that will only clear tracking info for a single entity: [`clear_inserted`](https://docs.rs/shipyard/0.5.0/shipyard/struct.SparseSet.html#method.clear_inserted), [`clear_modified`](https://docs.rs/shipyard/0.5.0/shipyard/struct.SparseSet.html#method.clear_modified) and [`clear_inserted_and_modified`](https://docs.rs/shipyard/0.5.0/shipyard/struct.SparseSet.html#method.clear_inserted_and_modified).

You can check tracking info for unique components with `is_inserted` (master only) and `is_modified`.
Clear with `clear_inserted` (master only) and `clear_modified`.
:warning: All 4 are associated functions and not methods.

----

That's a lot to take in, if you have any question, I'll be happy to answer.

**Comment by schell** [comment]
Thank you for the detailed answer! I think at this point I have a few questions:

> // only get the entities with both u32 and usize components where usize was inserted recently

That's cool! But here what does "recently" mean? My guess is since the last time it was cleared?

> When you want to clear insertion or modification tracking information from a storage

Does this clear the storage for all views or just _this_ view? For example if I have two systems which are both checking for transformation updates... 
Similarly, what about when I have a system that only checks for updates _sometimes_ - I guess this is where manual clearing comes in handy instead of using `ReaderId` with an `EventChannel` in specs...though I think that only works if the tracking happens per view.

Lastly, why change the API from 0.5 to master? I actually like the low-boilerplate and "lazy" style of the 0.5 tracking calls. My guess is that knowing at compile time gives you more opportunity to use optimized types?

Again, thank you for all this great work, I'm really looking forward to digging in.

**Comment by leudz** [comment]
> But here what does "recently" mean? My guess is since the last time it was cleared?

Yes, I hesitated to specify to it.

> Does this clear the storage for all views or just this view? 

Views don't have any state, they're like `RwLockReadGuard` and `RwLockWriteGuard`. So it'll be for all views.

If you have two systems checking tracking it could work out of the box. As long as you run them both before clearing they'll see the same tracking info.
Yes if you have a system only running sometimes you can make a storage and store things there.

Master's api change is not about performance, a few `if` have been removed but I don't think it made a big difference.
The main goal was to align intent and type system and getting rid of [`fast_iter`](https://docs.rs/shipyard/0.5.0/shipyard/trait.IntoFastIter.html) and [`fast_get`](https://docs.rs/shipyard/0.5.0/shipyard/trait.Get.html#tymethod.fast_get) in the process. In 0.5 when you get a mutable component it's wrapped in [`Mut`](https://docs.rs/shipyard/0.5.0/shipyard/struct.Mut.html). Since at compile time there was no way to know what the storage was tracking I had to always wrap components, then it would do something or not.
The problem is it prevented a few things. You weren't able to destructure the type easily and borrowing one field borrowed the entire struct (or you had to destructure it) #122.

This is not possible in 0.5 for example because you get `Mut<Position>` from the iterator:

```rust
struct Position(f32, f32);
fn run(mut positions: ViewMut<Position>) {
    for Position(x, y) in (&mut positions).iter() {
    }
}
```

`fast_iter` and `fast_get` were there to opt-out of this `Mut`. Using them gave a `&mut Position`.
But it wasn't the default and most (all? xD) people didn't use it. I can understand why.
With master's type info you only get a `Mut` when you are actually tracking _modification_.

Master's api is not perfect. Tracking the same component from multiple places is "dangerous". At work we use [`shipyard_app`](https://github.com/storyai/shipyard_app) to mitigate this. Bevy is doing something interesting there and it works great with a scheduler but I haven't found a way to make it work outside the scheduler too.
Someone on zulip also noticed it made it easier to add tracking to generic components. Instead of having to add tracking to each concrete type, you can make a generic implementation. 
Having to derive `Component` for everything has pros and cons. When I made shipyard it was one of the thing I didn't like about specs, I'm still not a huge fan.

---

I'd be very interested to know how your digging goes :smiley:

**Comment by schell** [comment]
Thanks again for the detailed explanation. I will let you know about my adventures :)
