### ISSUE TITLE
Systems scheduling optimization

### ISSUE THREAD

**Issue by mrazorvin** [leudz/shipyard#138]
Hello, can shipyard disable/skip system/workload if requested `View`s are empty? I suppose that I can check storage in system body manually, but will be cool if there will be some kind of way to do that in system declaration

To make my JS ECS works with a lot of systems more than +10000 (most of them was auto-generated for optimization purposes), I store all systems in something like double-linked list, and track if requested `View`s contains more than one element, and disable-enable corresponding system, so usually my game engine need to run only systems that currently has active elements and skip other ?

Sorry for my English :D

**Comment by leudz** [comment]
Thinking more about it, what I wanted to do might not be super useful.
You can borrow multiple kinds of views and I think only systems borrowing only `View` could be skipped.

`AllStoragesViewMut`, `UniqueView` and `UniqueViewMut` cannot be skipped because they are never empty.
`EntitiesViewMut` and `ViewMut` can be used to add components and entities so even empty it doesn't seems correct to skip.

Which leave us with `EntitiesView` and `View`. `EntitiesView` will likely not be empty very long. So really it's just `View`.
I'm afraid it'll have to be something inside or around the system.
