### ISSUE TITLE
Publically expose sparse_set::AddComponent?

### ISSUE THREAD

**Issue by thorjelly** [leudz/shipyard#140]
First, thanks for the good work on Shipyard. I am enjoying it over other rust ECS systems so far.

There are two AddComponent traits, one for World/AllStorage and the other for views. Only the trait for views appears to be publicly exposed. Why? Both seem useful and are required for public facing functionality.

I want to create a prefab system which works by having a Prefab component which contains a boxed closure which returns a set of components which will be added to the entity when it is run. However, I cannot return the correct type because sparse_set::AddComponent isn't exposed. Or am I missing something?

**Comment by leudz** [comment]
Thanks =)

I think the main reason was that I didn't made them public (probably because it's "only" used as bound) and nobody asked for it so far.

Last time I worked on this, I remember wanting to rename and move a few traits.
I still haven't found a good name for them, I might rename the ones for the views instead.
For now I prefixed them with "Tuple" but I'll probably change it when cleaning up for the 0.6 release.
