### ISSUE TITLE
Slow scheduling ?

### ISSUE THREAD

**Issue by mrazorvin** [leudz/shipyard#144]
Hi, following code snippet on my PC (after refresh) take ~1.4s to execute both with parallel and without parallel feature. But this doesn't make sense, because if I split this on 2 workloads: first with immutable borrows and second one with mutable borrows, I got ~800ms  

<details>
  <summary>scheduler testing</summary>
 
  ```rs
  #![feature(bench_black_box)]

use shipyard::{IntoIter, View, ViewMut, Workload, World};
use std::{hint::black_box, time::Instant};

struct Health(u32);
struct Position {
    x: f32,
    y: f32,
}

struct Hero(u32);

fn immutable_iter(positions: View<Position>, healths: View<Health>) {
    let mut result: i64 = 0;
    for i in 0..1_000_000 {
        result += black_box(result + i);
    }
    black_box(result);
}

fn mut_iter1(mut positions: ViewMut<Position>, mut healths: ViewMut<Health>) {
    let mut result: i64 = 0;
    for i in 0..1_000_000 {
        result += black_box(result + i);
    }
    black_box(result);
}

fn mut_iter2(mut healths: ViewMut<Health>, mut hero: ViewMut<Hero>) {
    let mut result: i64 = 0;
    for i in 0..1_000_000 {
        result += black_box(result + i);
    }
    black_box(result);
}

fn main() {
    let mut world = World::new();

    let mut work_load = Workload::builder("Int cycle");
    for i in 0..1000 {
        if i % 2 == 0 || i == 0 {
            work_load.with_system(&immutable_iter);
        } else {
            if i % 3 == 0 {
                work_load.with_system(&mut_iter1);
            } else {
                work_load.with_system(&mut_iter2);
            }
        }
    }


    work_load.add_to_world(&world).unwrap();

    let start_time = Instant::now();

    world.run_workload("Int cycle").unwrap();

    println!(
        "performance {:?}",
        Instant::now().duration_since(start_time)
    );
}
```
</details>

I though that scheduler should give performance boots even in cases like this

Do you interesting on creating own executor, instead of relay  on `rayon`?

I tested tested/created executor which run parallel everything what could be executed, then disable other thread and execute remains in single thread mode without atomic operations (it's also possible to re-order systems, based on execution time)

I can provide code, but don't know how to integrate wtih shipyard

**Comment by leudz** [comment]
Hi, could you say more about what you expect happen?
You are interleaving `immutable_iter` with either `mut_iter1` or `mut_iter2`, nothing runs in parallel.
When you split immutable and mutable then all immutable will try to run in parallel and the mutable sequentially.

**Comment by mrazorvin** [comment]
@leudz I expected similar performance in both cases

**Comment by mrazorvin** [comment]
@leudz I expected such behavior because of this documentation https://leudz.github.io/shipyard/guide/master/going-further/parallelism.html,

```
As long as the "parallel" feature is set (enabled by default) workloads will try to execute systems as much in parallel as possible. There is a set of rules that defines the "possible":
```

**Comment by leudz** [comment]
Ok so you expect the workload to put all immutable first and then all mutable or the other way around so that it runs as many systems in parallel as possible. Yeah because of this sentence, I was thinking about it.

This sentence was difficult to write. It will reorder stuff but it will keep the "state of data" intact.
So it will try to run systems in parallel as long as running sequentially and in parallel doesn't affect the components.
This is the relevant part of the doc:
> There is a set of rules that defines the "possible":
>
>    - Systems accessing AllStorages stop all threading.
>   - **There can't be any other access during an exclusive access, so ViewMut<T> will block T threading**.
>
> When you make a workload, all systems in it will be checked and batches (**groups of systems that don't conflict**) will be created.

A simple example of that:

```rs
#[derive(Component, Debug)]
struct Int(u32);

fn increment(mut int: UniqueViewMut<Int>) {
    int.0 += 1;
}

fn is_even(int: UniqueView<Int>) {
    if int.0 % 2 == 0 {
        println!("even {int:?}");
    }
}

fn main() {
    let world = World::new();
    world.add_unique(Int(0));

    world.add_workload(|| (is_even, increment, is_even, increment, is_even, increment));
    world.run_default().unwrap();
}
```

In this example running sequentially or in parallel will always print "even Int(0)" and "even Int(2)".
If systems could be reordered more then you could have "even Int(0)" or "even Int(2)" twice or none.

----

This is not to say that it will always be like that. Bevy's scheduling allows for complete reordering by default.
I'm adding `before`/`after` syntax soon and this will enable this kind of scheduling. Without it you wouldn't know what could happen at runtime.

**Comment by mrazorvin** [comment]
Makes sense. In fact, will be enough to has something like sync_point

for example:
```
sys1
sys2
sys3
sys4
syn_point <- everything before that will be executed in parallel as much as possible
```

**Comment by mrazorvin** [comment]
What do you think about API for updating values during immutable borrows? 
 
Because SparseSet already has additional collections for tracking deleted/removed components.  
It should be fairly easy to add new collection which will store updates in following form `Vec<Box<Fn>>` (+ AtomicUsize  for vec length for parallel execution)

```rs
fn calc_hero_hp(attributes: View<Attribute>, monsters: View<Monster>, effects: View<Effect>)  {
   let hero_entity_id = ... // Looking Hero entity_id inside monster View
   let hp_delta = ...       // Some Heavet's say computations that required iterating a lot of effects  
   attributes.async_update(hero_entity_id, |attribute| {
      attribute.hp += hp_delta;
   });
}
```

Such updates will be applied during `syn_point` (without ordering guaranty). 

This feature could helps a lot when you need to change only few components in entire View, but calculating updates required some HEAVY computations, that could block other views

**Comment by leudz** [comment]
> What do you think about API for updating values during immutable borrows?

I'm not a big fan because it makes it harder to understand how components are modified.

Let's say one day you have a weird bug where the hero's HP are underflowing.
You debug it and find out that it happens during a sync point.
Now you have to check all places where you have an `Attribute` `async_update`.

> This feature could helps a lot when you need to change only few components in entire View, but calculating updates required some HEAVY computations, that lock other system (because of blocked views)

Why not split the system?
First a system that makes the heavy computation and store the result in another component.
Then a very lightweight system that applies the result.

> The second use-cases, is systems that controlling AI usually they needed access to large-amount of components, but the end affect same (Position,Direction) component, which basically means that we can't run them in parallel

I would suggest again to have more systems. I recently spoke with someone about Utility AI.
With Utility AI you first have systems that look at the world (immutably) and generate scores.
Then scores are checked and actions are decided.
Finally actions are taken and modify the state of the world.

**Comment by mrazorvin** [comment]
Got it, feel free to close this issue, I suppose most of this features is outside of current Shipyard scope. Since I need some of them I will try implement them by myself =D

> I'm not a big fan because it makes it harder to understand how components are modified.

I'am still thinking that this will be a good utility to helps optimize code is some edge cases 

> Why not split the system?

Sounds like redux action from JavaScript world, I don't like boilerplate code, so I happy to write less code, but pay with updates ordering

 > Utility AI
 
 I also red about this, and even have plans to use it, but again, instead of splitting into two separate steps, I prefer to has everything as close as possible together

**Comment by leudz** [comment]
Ok ok, you should be able to create any kind of scheduler, I don't use any internal-only method. There is just a lot of type magic to be able to have a nice syntax.
