### ISSUE TITLE
how to move View<..> to thread?

### ISSUE THREAD

**Issue by PudgeKim** [leudz/shipyard#160]
```
fn my_system(my_views: View<MyView>) {
  ...
  std::thread::spawn(move || {
    let OK(..) = my_views.get(id) else { .. }
  });
```

I need to use some component in the thread. 
I tried as below but it doesn't work.

```
let my_views_ref = &my_views; // compiler says it doesn't live long enough
let thread1 = std::thread::spawn(move || {
  my_views_ref.get(id).. // borrowed data escapes out of function..
```

what's the best way to use View or ViewMut in a thread?

-------

After thinking of it, I think the reason the compiler gives me an error is a thread can outlive the function.
What I want to do is creating three threads in a system and running them in parallel. Because this system is heavy.
One for calculating some heavy work + sending data and Two for receiving data + setting data to component or something else.
Is there any way to do it?

**Comment by leudz** [comment]
You are correct the thread could outlive the function and that's all the type system knows.
Since 1.63 there is another function [`scope`](https://doc.rust-lang.org/std/thread/fn.scope.html) to do what you want.

Because it's a system i'm going to assume it'll run multiple times. It might be good to use a rayon thread pool to not spawn new threads each time.
It would be almost identical to std's `scope`, [`rayon::scope`](https://docs.rs/rayon/latest/rayon/fn.scope.html).
I think the only risk with using `rayon` here is that it's not guaranteed that the work will be spread on multiple threads. So if you use something like a `Mutex`, it could deadlock or panic.
