### ISSUE TITLE
Is there any way to add multiple tracking options to component except #[track(All)]?

### ISSUE THREAD

**Issue by notinmybackyaard** [leudz/shipyard#173]
In some situations, I need a component that implements both removed() function and inserted() funtion.
But only way to activating multiple options is give #[track(All)] derive to component.
And if so, there's made unnecessary deleted infomation. That's why I want to avoid All option to components.
I tried like below but no one succeed.
1. 
#[track(Insertion, Removal)]
2. 
#[track(Insertion)]
#[track(Removal)]
Is there any way that I missed?

And here's another question, I heard that component with Deleted tracking option has to be cleared manually
outside of workloads. And I confirmed that when I using Deleted option component without clear, memory continue to increase.
Then, which is proper way to clear deleted information? I just want to clear all deleted information, If all systems read that component.
I think I would write a code like below, Is this valid code?
```
            let timestamp = self.world.get_tracking_timestamp();

            self.world.run_workload(main_workload).unwrap();

            self.world.clear_all_removed_or_deleted_older_than_timestamp(timestamp);
```
If not, would you show me a sample code?
I know you are busy, but your reply will be great help for me! 🙏

**Comment by leudz** [comment]
With 0.6 `#[track(All)]` is your only solution. Each combination involved a non trivial amount of code so I ended up with some combinations missing.

> I heard that component with Deleted tracking option has to be cleared manually outside of workloads.

This is partially correct. As you saw not clearing deleted info will increase memory forever but you can clear inside workloads. For that you just need a `ViewMut` and call [`clear_all_deleted`](https://docs.rs/shipyard/latest/shipyard/struct.ViewMut.html#method.clear_all_deleted). Since you don't use this information you can have a system at the end of your `main_workload` that clears deletions info.

----

With master you can now choose any tracking combination you want. In the system where you need `removed` and `inserted` you would borrow `ViewMut<T, {track::Inserted + track::Removed}>` and deleted info would never be created.
The documentation for this is not updated yet but you can read a bit more on it [here](https://shipyard.zulipchat.com/#narrow/stream/269448-update/topic/On.20demand.20tracking/near/325747110).

**Comment by notinmybackyaard** [comment]
Thanks for your detailed answer. But I wonder if the code which I showed you is not a valid or proper way? I think it's more convenient than writing a clear_all_deleted code inside each component's workloads if it works.

**Comment by leudz** [comment]
It would kind of work but you'd probably loose removed info too soon. You might want to add a loop/frame of delay.

**Comment by notinmybackyaard** [comment]
Okay, maybe I'll add some counter code. It helped me a lot, thank you 🙇
