### ISSUE TITLE
Can I run some systems in parallel if UniqueViewMut is thread-safe?

### ISSUE THREAD

**Issue by PudgeKim** [leudz/shipyard#178]
I have unique struct which is thread-safe because of DashMap.
```
#[derive(Unique)
struct MyMap {
  m: DashMap<EntityId, Bag>
}

unsafe impl Send for MyMap {}
```

some systems need `mut my_map: UniqueViewMut<MyMap>`
Even though it is `UniqueViewMut`, it is thread-safe. so I want to run systems in parallel. (if other parameters are View or UniqueView)
Is there anyway to do it?

** which source code file is related to it?

**Comment by leudz** [comment]
No you can't have 2 `UniqueViewMut<MyMap>` at the same time because there is an exclusive reference inside (`&mut MyMap` basically).
Since it's thread safe you can use `UniqueView<MyMap>` and you'll still be able to modify it.

----

Btw you shouldn't need `unsafe impl Send for MyMap {}`, it should "inherit" it from `DashMap`.

**Comment by PudgeKim** [comment]
oh `DashMap`'s `get_mut` is `&self` instead of `&mut self`. so I can use `UniqueView`.
