### ISSUE TITLE
Cannot create Unique component with non-sync wgpu properties in WASM demo

### ISSUE THREAD

**Issue by Umenokin** [leudz/shipyard#186]
I am trying to use WGPU with the shipyard.
I created `Unique` component which right now only has WGPU surface, device, and queue:
```
#[derive(Unique)]
pub struct Render {
    pub(crate) surface: wgpu::Surface,
    pub(crate) device: wgpu::Device,
    pub(crate) queue: wgpu::Queue,
}

...

app.world.add_unique(Render {
        surface,
        device,
        queue
 });
```

As a result, I am getting an error:
```
`(dyn wgpu::context::DynContext + 'static)` cannot be shared between threads safely
the trait `Sync` is not implemented for `(dyn wgpu::context::DynContext + 'static)`
required for `Arc<(dyn wgpu::context::DynContext + 'static)>` to implement `Send`
```
From wgpu thread it is now clear that WGPU in WASM is !Sync + !Send. But it seems the shipyard's bunnies demo is working but I cannot find any special configurations.

Thanks! 🙏

**Comment by leudz** [comment]
I don't know why you have something `!Send + !Sync` where the bunny demo doesn't. Maybe `wgpu` changed, the demo uses `wgpu` 0.15 which is not the latest version.

Regardless of why, if you have a `!Send`/`!Sync` type you can still store it in `World`, you'll need to add the `thread_local` cargo feature to shipyard.
Then use [`World::add_unique_non_send_sync`](https://docs.rs/shipyard/latest/shipyard/struct.World.html#method.add_unique_non_send_sync) instead of `World::add_unique`.
Finally when you borrow/define a system you'll have to use `NonSendSync<UniqueView<Render>>` instead of `UniqueView<Render>`.

Note: adding `thread_local` feature will make `World: !Send`

**Comment by Umenokin** [comment]
Thank you, @leudz! Your explanation worked perfectly! I was confused by combination of factors that wgpu removed Send Sync from version 0.16 and that it is not `add_unique` which will act differently but dedicated method `add_unique_non_send_sync`. So what I have now is this:

```
    #[cfg(feature = "web")]
    pub fn add_unique<T: Unique>(&mut self, component: T) -> &mut Self {
        self.world.add_unique_non_send_sync(component);
        self
    }

    #[cfg(not(feature = "web"))]
    pub fn add_unique<T: Send + Sync + Unique>(&mut self, component: T) -> &mut Self {
        self.world.add_unique(component);
        self
    }
```

**Comment by Umenokin** [comment]
@leudz are there other limitations? I am using workloads and when I add system with `|mut render: NonSendSync<UniqueView<Render>>| {` it will panic. Even if my Render is empty struct without !Sync properties. And works fine if I do it this way ``|mut render: UniqueView<Render>`. It panics not when add into workload but when run workload of multiple systems. Can you actually mix sync and non sync systems inside one workload?

**Comment by Umenokin** [comment]
@leudz thank you for your support. I did not find the solution to this problem but closing the ticket because of migration to another ECS.
