### ISSUE TITLE
A weird atomic value of borrow field in ViewMut struct

### ISSUE THREAD

**Issue by EclipseDaebak** [leudz/shipyard#213]
```
/// Exclusive view over a component storage.
pub struct ViewMut<'a, T: Component, Track = <T as Component>::Tracking> {
    pub(crate) sparse_set: &'a mut SparseSet<T>,
    pub(crate) all_borrow: Option<SharedBorrow<'a>>,
    pub(crate) borrow: ExclusiveBorrow<'a>, // This field is weird
    pub(crate) last_insertion: TrackingTimestamp,
    pub(crate) last_modification: TrackingTimestamp,
    pub(crate) last_removal_or_deletion: TrackingTimestamp,
    pub(crate) current: TrackingTimestamp,
    pub(crate) phantom: PhantomData<Track>,
}
```

Suppose I have a component called ComponentA.
I have the following system.
```
fn my_system1(
mut my_components: ViewMut<ComponentA>
...
) {
...
}
```

The system above runs in infinite loop.
I always get 9223372036854775808 when I print the AtomicUsize in `borrow: ExclusiveBorrow<'a>`.
(To get the atomic value I used `load` method.)
so when I call `my_components.as_view()` method, atomic value is overflowed by `read_reborrow`.

```
#[inline]
    pub(super) fn read_reborrow(&self) -> (SharedBorrow<'_>, usize) {
        let new = self.0.fetch_add(1, Ordering::Acquire) + 1;

        self.check_overflow(new);

        (SharedBorrow(self), new)
    }
```

why not start with 0? (+ why is it not increasing?)
what's the problem? my version is 0.7.3

**Comment by leudz** [comment]
> I always get 9223372036854775808
> why not start with 0? 

That's expected. The `BorrowState` is a runtime version of the borrow checker, like `RwLock` but instead of waiting when the lock is held, it returns an error. So it has to handle both reads and write, atomically because multiple threads could try to read/write to it at the same time.
Since there can be one write and multiple reads, reads are represented by incrementing by 1 for each read. Write is represented by the highest 64 bit. That would be 9223372036854775808, you can use the `{:b}` formatter to see better what is happening.

> (+ why is it not increasing?)

That's a problem, it should increment by 1.
When calling `as_view`, `BorrowState` is in an temporary invalid state, we have both reads and write at the same time. But the borrow checker makes sure the reads will be dropped before the write is mutated again.
But that's not what is happening, the counter doesn't change.
The issue was actually in the `shared_reborrow` method. `read_reborrow` returns a `SharedBorrow` that is dropped immediately, decrementing the counter.

https://github.com/leudz/shipyard/blob/82e6e305e8ca3dc41ca69603d57d97d8378a3143/src/atomic_refcell/borrow_state.rs#L30-L34

----

Thanks for reporting it! A new version is available with the fix.

**Comment by leudz** [comment]
No problem!

`&*some_components` is a bit faster since it doesn't do anything whereas `as_view` updates the `BorrowState` and copies the fields.

It can be useful if you call a system from within another system. It's a niche function but it's there in case there is no other way.
For example:

```rust
fn sys_a(vm_compA: ViewMut<A>) {
    // some stuff here

    sys_b(vm_compA.as_view());
}

fn sys_b(v_compA: View<A>) {}
```

`sys_b` cannot use a reference or it wouldn't work as a system anymore.
