### ISSUE TITLE
Entity creation verbosity

### ISSUE THREAD

**Issue by cart** [leudz/shipyard#78]
Entity creation is currently quite verbose:

```rust
world.run(
    |mut entities: EntitiesViewMut,
        mut a: ViewMut<A>,
        mut b: ViewMut<B>,
        mut c: ViewMut<C>,
        mut d: ViewMut<D>,
        mut e: ViewMut<E>,
        mut f: ViewMut<F>,
        mut g: ViewMut<G>,
        mut h: ViewMut<H>| {
        entities.add_entity(
            (
                &mut a, &mut b, &mut c, &mut d, &mut e, &mut f, &mut g, &mut h,
            ),
            (
                A::default(),
                B::default(),
                C::default(),
                D::default(),
                E::default(),
                F::default(),
                G::default(),
                H::default(),
            ),
        );
    },
);
```

This makes sense in the context of a system where arbitrary type borrows can (and should) be discouraged.

Ideally there would also be an api that is closer to this for world initialization:

```rust
world.add_entity(
    (
        A::default(),
        B::default(),
        C::default(),
        D::default(),
        E::default(),
        F::default(),
        G::default(),
        H::default(),
    )
);
```

Or maybe something like
```rust
world.run(|mut all_storages: AllStorages|
    all_storages.add_entity(
        (
            A::default(),
            B::default(),
            C::default(),
            D::default(),
            E::default(),
            F::default(),
            G::default(),
            H::default(),
        ),
    );
);
```

**Comment by leudz** [comment]
There was a time when it was possible, it was removed in 0.2 or 0.3.

Only being able to access components and entities through their storage has a big advantage: you can look for `ViewMut<T>` in your whole codebase and find every place where this storage is modified.
Currently it also has performance implications, every call to `World::add_entity` would lock/unlock 1 + component_count times.

> This makes sense in the context of a system where arbitrary type borrows can (and should) be discouraged.

It's not arbitrary and you'd have to specify which types you're borrowing or write that you're borrowing `AllStorages`.

**Comment by colelawrence** [comment]
This seems like a case that would happen few times in a codebase.

The only places this happens in my codebase is during seeding, and yes it's a bit verbose, but in the actual code in my systems, I'm mostly changing or adding only a 2-3 components at a time. If it were very common to add/set 5 components at a time, that would be a code smell in my application's codebase (why are these components not grouped into one component, for example).

For your codebase, if this isn't a code smell, I'd like to know more about the use case.

**Comment by cart** [comment]
I definitely agree that being able to do a search for ViewMut and find all mutations is valuable. I also fully concede the value  of my `This makes sense in the context of a system where arbitrary type borrows can (and should) be discouraged.` comment. Its just wrong :smile:   

We have a couple of threads going so ill separate this into sections:

#### @colelawrence 's comment:
> If it were very common to add/set 5 components at a time, that would be a code smell in my application's codebase (why are these components not grouped into one component, for example).
>
>For your codebase, if this isn't a code smell, I'd like to know more about the use case.

In my opinion merging commonly used components into a single component is actually more of a "code smell" in ECS as you are now tightly coupling both data and functionality. For example: if i'm commonly creating an entity with the ```Position```, ```Parent```, ```Person```, ```Inventory```, and ```Health``` components, then merging them into a single ```Person { Position, Parent, Inventory, Health } ``` component now means that I need to write separate systems for another entity type that contains ```Position```, ```Parent```, ```Monster```, ```Inventory```, and ```Health``` (which would be ```Monster { Position, Parent, Inventory, Health }``` if we merged them because they are "frequently used together"). I personally want to have a ```health_system(Health)```, a ```hierarchy_system(Parent, Position)```, a ```inventory_system(Inventory)```, etc. Not a single 

```
person_system(Person) { 
  health_thing(person.Health); 
  inventory_thing(person.Inventory);
  hierarchy_thing(person.Position, person.Parent)
}
``` 

Additionally smaller components are more cache friendly because you aren't pulling in uber MegaPerson components into systems that only operate on a person's Health.

In my personal opinion "small" components with a single responsibility are almost always better in ECS.


#### searching for component mutations vs ergonomics
I value code ergonomics pretty highly (there is a trend in the issues I've been filing :smile: ). Verbosity often makes author intent less clear and makes apis harder to consume. I personally value improving the ergonomics of entity creation much higher than I value the ability to search for all component writes in a codebase.

Which of these two operations will be more common: "inserting an entity" or "searching the codebase for all systems mutating a specific component"?

Additionally, shouldn't searching for ```ViewMut<Thing>```, ```MyComponent::constructor```, and ```MyComponent {```  be almost as effective?

**Comment by leudz** [comment]
> "inserting an entity"

Inserting an entity with the `World` directly and not modifying it soon after.
It would be strongly recommended to not use it in systems since it would make them error prone or block any threading. Plus the access to `World` is not meant to stay.

So how often do I create entities not using systems: not often. The "all together" chapter of the guide for example creates all non unique components in systems.

> Additionally, shouldn't searching for ViewMut<MyComponent>, MyComponent::constructor, and MyComponent { be almost as effective?

With the method you used in the first post, it's 3 things to search. That's not even counting free functions or methods on other types that could return this type.

---

This method also wouldn't work for `!Send` or `!Sync` types.
```rust
world.run(
    |mut entities: EntitiesViewMut,
     mut u32s: ViewMut<u32>,
     mut rcs: NonSendSync<ViewMut<Rc<usize>>>| {
        entities.add_entity((&mut u32s, &mut *rcs), (0, Rc::new(1)));
    },
);
```
Would become:
```rust
let entity = world.run(
    |mut entities: EntitiesViewMut, ref mut u32s: ViewMut<u32>| entities.add_entity(u32s, 0),
);

world.run(|entities: EntitiesView, mut rcs: NonSendSync<ViewMut<Rc<usize>>>| {
    entities.add_component(&mut *rcs, Rc::new(1), entity);
});
```

**Comment by cart** [comment]
That makes sense. I understand your position and it is definitely valid. This is probably just a situation where we value things differently. Fortunately I also think this is a situation where we can both have what we want. I'm pretty sure I can build something like this without making changes to shipyard:

```rust 
let entity = world.build_entity() // add method using trait extension
  .add_component(ThingA)
  .add_components((ThingB, ThingC))
  .finish()

// add_components would internally call this
world.run(|mut entities: EntityViewMut, mut a: ViewMut<A>, mut b: ViewMut<B>)| {
 entities.add_entity((&mut a, &mut b), (A, B));
});
```
I'm pretty sure I would need to make a macro to create the builder struct, but thats not a big problem. I _personally_ think this should be common code available to all shipyard users, but I'm also perfectly comfortable just having that as a feature in my (soon to be released) engine.

**Comment by leudz** [comment]
It's 100% possible, it could even go in the recipes.

I think the simplest way to build it would be to call `entities.create_entity((), ())` in `build_entity` and keep the `EntityId` in the builder struct.
Then you could call `add_component` or even better `add_component_unchecked` when it's available.
You would just have the extension trait and the builder struct.

For an engine legion might be a better fit, no packs to think about. [Bevy Engine](https://bevyengine.org/)

**Comment by cart** [comment]
Cool thats definitely helpful. Yeah packs were my biggest concern. With legion you essentially get packs for "free" but it comes at the cost of more expensive add/remove component operations. I'd love to be able to use components as "tags / indices" that are added or removed frequently. Legion makes that model difficult.

If you have time and you're open to it, I'd love to discuss your opinion on legion vs shipyard for a general purpose engine (maybe on zulip).

**Comment by cart** [comment]
I'm also _very_ drawn to the new system definitions in shipyard. They're just really nice to type and they're super legible. Legion is a big step down in that regard.

**Comment by colelawrence** [comment]
@cart thank you for the code samples and discourse on this topic. For the moment, I lean towards this being easy to attain as an addition to shipyard (like a recipe) rather than a part of shipyard.

I can too easily see bottling up a component builder obfuscating the performance implications. shipyard can no longer reason about systems to be run in parallel if any system chooses to use the builder pattern (if I understand correctly).

Fortunately, from this conversation, it sounds like this is approachable without adding another way to work with components in shipyard.

Thank you also for sharing your perspective on how you view components. I'm in full alignment on your perspective. In fact, I would carry the sentiment of having small reuseable component s most of the time, and apply it to having small systems most of the time. (As in systems that declare the "locks" they require to make it easier to reason about performance and encourage systems with fewer responsibilities).

I'd be happy to hear all additional thoughts that come to mind on this front!

**Comment by leudz** [comment]
I've been thinking about this issue, multiple times.

`!Send` and `!Sync` components are not an issue.

For performance, in general it's not a problem and the solution in the long run will be bulk operations.

The biggest problem I have is still the fact that it's not as clear as other methods borrowing storages and it would open the door for other methods like it.
But there will be other features that aren't super clear on mutation, `World::maintain` for example or events.
I suppose a strict rule can't exist and I have to decide on a case-by-case basis.

It could be a recipe of course but I'm not sure it would be the right place. People might miss it since the doc, guide and tutorial will mention it once or twice but won't use it.
