### ISSUE TITLE
Way to directly grab entity by EntityId

### ISSUE THREAD

**Issue by djahandarie** [leudz/shipyard#81]
I have lots and lots of instances of code like this:

```rust
self.world.run(|ref mut things: ViewMut<Thing>| {
  things.get(id).blah = 3;
});
```

I feel like it'd be much nicer if this were:
```rust
self.world.get(id, |ref mut thing: Thing| {
  thing.blah = 3;
});
```
(Maybe `run_get` is a better name. Could see a parallel with `borrow_get`.)

Apologies if getting entities by ID is an anti-pattern, or if there's already some way to do this.

**Comment by leudz** [comment]
Getting entities by id can be very common or totally absent based on what you build. Borrowing from `World` to assign to a field seams weird.

In case you have just one instance of `Thing` in the `World`, a [unique storage](https://leudz.github.io/shipyard/book/going-further/other-component-storage.html#unique-storages) would make it a lot nicer.

If you have multiple instances I personally would go with `borrow`:
```rust
(&mut self.world.borrow::<ViewMut<Thing>>())
    .get(id)
    .blah = 3;
```

Since this is a very uncommon thing to do, and not recommended, I don't think I'll add it to the library. But you can define something on your side, on the type of `self` or as a `World` extension trait.

I don't think your definition can exist as is, you'll have to specify mutation and the view type. It can be done in a few ways based on if you care about `!Send` and `!Sync` types or not, if you (dis)like the turbofish syntax,...

**Comment by djahandarie** [comment]
For context, I’m using shipyard in the context of a Yew webapp. It’s working *incredibly* well for state management. I occasionally have EntityIds as part of my entity types, for example when I have a list of things, to track which entities are in that list.

The reason I have lots of mutations of single entities by their ID is because everything is driven by message passing of the ID. I.e., when you edit an input field, a callback gets triggered which tells the app that EntityId x got modified in this way, and the handler of that message looks up x and modifies it appropriately.

I changed my message handler to just be only single giant run with the match inside of the run and that has improved the ergonomics considerably, however.

**Comment by leudz** [comment]
Oh, that explains the many id access.
> a list of things, to track which entities are in that list

You can sometimes model it with a [tag component](https://leudz.github.io/shipyard/book/going-further/other-component-storage.html#tag-components).
